#!/usr/bin/env python3
"""Build BeliefTrace's public-only static GitHub Pages site. No dependencies."""
from pathlib import Path
from html import escape
import json
import shutil

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "dist"
BASE = "/belieftrace"
ORIGIN = "https://shinywesley.github.io"
DATE = "September 12, 2026"
SUPPORT = "aicalorietracker@gmail.com"
CONFIG = json.loads((ROOT / "release.json").read_text())


def link(path, text, extra=""):
    return f'<a href="{BASE}{path}" {extra}>{text}</a>'


def document(title, deck, body):
    return f'<div class="document-head"><p class="eyebrow">BeliefTrace / Information</p><h1>{title}</h1><p class="deck">{deck}</p><p class="updated">Updated {DATE}</p></div><article class="document">{body}</article>'


def section(title, body):
    return f'<section><h2>{title}</h2>{body}</section>'


def contact():
    return f'<p>BeliefTrace is operated by <strong>Wesley Jaynes</strong>. For support, privacy, security, or rights questions, email <a href="mailto:{SUPPORT}">{SUPPORT}</a>.</p>'


def page(path, title, description, body):
    canonical = f"{ORIGIN}{BASE}{path}"
    nav = ''.join(link(p, label, 'aria-current="page"' if path == p else '') for p, label in [('/#explore','Explore'),('/support/','Support')])
    footer = ''.join(link(p, label) for p, label in [('/privacy/','Privacy'),('/terms/','Terms'),('/support/','Support'),('/safety/','Safety'),('/data/','Your data')])
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><meta name="theme-color" content="#10151b"><title>{escape(title)} · BeliefTrace</title><meta name="description" content="{escape(description, quote=True)}"><link rel="canonical" href="{canonical}"><link rel="stylesheet" href="{BASE}/assets/site.css"><link rel="icon" href="{BASE}/assets/icon.png"><meta property="og:type" content="website"><meta property="og:site_name" content="BeliefTrace"><meta property="og:title" content="{escape(title, quote=True)}"><meta property="og:description" content="{escape(description, quote=True)}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{ORIGIN}{BASE}/assets/icon.png"><meta property="og:image:width" content="1024"><meta property="og:image:height" content="1024"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="{escape(title, quote=True)}"><meta name="twitter:description" content="{escape(description, quote=True)}"></head>
<body><a class="skip" href="#main">Skip to content</a><header><a class="brand" href="{BASE}/"><img width="36" height="36" src="{BASE}/assets/icon.png" alt=""><span>BeliefTrace</span></a><nav aria-label="Main">{nav}</nav></header><main id="main">{body}</main><footer><div><a class="brand" href="{BASE}/">BeliefTrace</a><p>For the questions that stay with you.</p><p class="muted">© 2026 Wesley Jaynes</p></div><nav aria-label="Information">{footer}</nav></footer></body></html>'''


def build():
    OUT.mkdir(exist_ok=True)
    assets = OUT / 'assets'; assets.mkdir(exist_ok=True)
    shutil.copyfile(ROOT/'assets/site.css', assets/'site.css')
    shutil.copyfile(ROOT/'assets/icon.png', assets/'icon.png')
    thinkers = ''.join(f'<li><span class="thinker-no">0{i}</span><div><h3>{name}</h3><p>{theme}</p></div><span aria-hidden="true" class="thinker-dot dot-{i}"></span></li>' for i,(name,theme) in enumerate([('Immanuel Kant','Duty · freedom · the limits of knowledge'),('John Locke','Experience · identity · political liberty'),('Karl Marx','Work · power · social change'),('Niccolò Machiavelli','Leadership · conflict · political judgment'),('Thomas Hobbes','Security · authority · the social contract')],1))
    paid = 'A weekly subscription is in preparation. Its full price and included answer allowance will be shown together before purchase.'
    if CONFIG.get('weekly_price_usd') is not None and CONFIG.get('weekly_answers'):
        paid = f"BeliefTrace Plus includes {CONFIG['weekly_answers']} successful answers per verified weekly subscription period, with no rollover. The United States price is ${CONFIG['weekly_price_usd']:.2f} per week; Apple shows the full localized price before purchase."
    home = f'''<section class="hero"><p class="eyebrow">An intellectual atlas for iPhone</p><h1>A good question<br> opens a <em>world.</em></h1><div class="hero-bottom"><p>Talk through the ideas that shape a life. Follow an answer into the beliefs, sources, and connections behind it.</p><a class="button" href="#explore">Take a closer look <span aria-hidden="true">↗</span></a></div><div class="release-note"><span class="status-dot" aria-hidden="true"></span><p>The next iPhone release is in preparation. Public download and subscriptions are not available yet.</p></div></section>
<section id="explore" class="explore"><div class="section-heading"><p class="eyebrow">A conversation worth following</p><h2>Understand the answer.<br> Then go deeper.</h2></div><div class="journey"><article><span class="step">01 / Ask</span><h3>Start with something<br> that matters.</h3><p>Bring a question about freedom, ambition, work, or a life well lived. Explore a documented perspective in your own words.</p></article><article><span class="step">02 / Inspect</span><h3>See what supports<br> the answer.</h3><p>Open ideas and sources beside an answer. Distinguish cited evidence from related material, and notice where support is missing.</p></article><article><span class="step">03 / Connect</span><h3>Follow an idea<br> somewhere new.</h3><p>Explore an interactive belief map, inspect connections, and return to the conversation with a better question.</p></article></div></section>
<section class="thinkers"><div><p class="eyebrow">Five perspectives in preparation</p><h2>Meet an idea<br> at its source.</h2><p class="section-deck">The next release centers on five documented philosophical perspectives. These are AI interpretations, with evidence and limits made visible.</p></div><ol>{thinkers}</ol></section>
<section class="principle"><p class="eyebrow">Intellectual curiosity, with care</p><h2>An interpretation.<br> <em>An invitation to think.</em></h2><p>BeliefTrace does not reproduce a historical person. Generated prose is not an authentic quotation. Sources help you inspect an answer; they do not make AI infallible.</p>{link('/safety/','Read about accuracy and safety <span aria-hidden="true">↗</span>','class="text-link"')}</section>
<section class="access"><div><p class="eyebrow">Room to explore</p><h2>Five answers<br> to begin.</h2></div><div><p class="large-copy">The next release includes five successful free answers in total, across thinkers and conversations.</p><p>Reading old conversations, exploring maps, and opening sources does not use an answer. A service error without a usable answer does not spend your allowance.</p><p>{paid}</p>{link('/terms/','Read the subscription terms <span aria-hidden="true">↗</span>','class="text-link"')}</div></section>
<section class="faq"><p class="eyebrow">A few useful answers</p><h2>Before you begin.</h2><details><summary>Is this a conversation with the real person?</summary><p>No. BeliefTrace presents AI interpretations of documented ideas. Historical people and their estates do not endorse the app. Always distinguish generated interpretation from an explicitly sourced quotation.</p></details><details><summary>Where do my conversations live?</summary><p>Conversations are stored on your iPhone. The mobile app has no BeliefTrace account or cloud chat synchronization. A question and limited recent context are sent to the service and OpenAI only after AI-processing consent.</p>{link('/privacy/','Read the privacy policy')}</details><details><summary>Does exploring a map use an answer?</summary><p>No. The allowance applies to completed answers to questions and follow-ups. Browsing maps, sources, and existing conversations is free.</p></details><details><summary>Can I use it offline?</summary><p>Saved conversations and previously cached material can be read offline. New answers and uncached source or graph content need an internet connection.</p></details><details><summary>How can I get help?</summary><p>Email <a href="mailto:{SUPPORT}">{SUPPORT}</a>. Include your app version and public error code. Please leave private conversations and credentials out of ordinary support emails.</p></details></section>'''
    privacy = section('At a glance','<p>This policy covers the BeliefTrace iPhone app and this information website. The next iPhone release is still in preparation. The mobile app uses a pseudonymous installation identity and local conversation storage. It does not offer a BeliefTrace login or silently synchronize existing chats.</p>')
    privacy += section('Your questions and AI processing','<p>Before the first AI request, the app asks for consent to send your question and a limited portion of recent conversation context to the BeliefTrace service and OpenAI. Relevant source passages may also be sent to help produce an answer. These requests are processed for generation, evidence checks, and necessary reliability steps.</p><p>Do not include information you would not want these services to process. Withdrawing consent stops new AI requests; it does not retract information already processed.</p><p>OpenAI’s default API policy does not use API data to train models unless the customer opts in. Default abuse-monitoring logs may include prompts and responses and be retained for up to 30 days, or longer when legally required. This is not a promise of zero retention or confirmation of special account-level controls. See <a href="https://platform.openai.com/docs/guides/your-data">OpenAI’s data controls</a>.</p>')
    privacy += section('Local records and short-term recovery','<p>Conversations, drafts, saved preferences, and cached graphs remain on your iPhone. Deleting or losing this local data can permanently remove it; restoring a purchase does not restore chats.</p><p>The next release temporarily retains completed answer responses on the server for up to 48 hours so a disrupted delivery can be recovered without generating or charging twice. This recovery copy is encrypted at rest and can be erased from Settings without a subscription. Content expires after 48 hours and is physically purged during scheduled cleanup; protected backups may retain it under the backup retention policy. It is separate from your local conversation history and is not a cloud-sync service. It contains answer and evidence content; it is not routine analytics.</p>')
    privacy += section('Identity, allowances, and security','<p>The service uses pseudonymous installation and purchase identifiers to authenticate requests, maintain your remaining allowance, prevent duplicate charges, and protect provider budgets. Apple App Attest supplies app-integrity information. Network and request metadata may be processed for rate limiting and security.</p><p>A minimal server ledger retains lifetime free-answer consumption and subscription-period grants beyond the short request-recovery window. Reinstalling is not a reliable way to restore local history, and the installation identity is not proof of one unique human. Content-free request receipts, subscription grants, and spend diagnostics are retained for up to 400 days. Lifetime trial balances, restore aliases, and hashed transaction mappings remain while the pseudonymous identity exists. These necessary enforcement records are not reset when local chats are deleted.</p>')
    privacy += section('Purchases and service providers','<p>Apple processes subscription purchases and payment instruments. RevenueCat processes pseudonymous customer identifiers, purchase and subscription state, transaction history, app and device information, and relevant diagnostics to verify access and provide purchase restoration. BeliefTrace does not receive your full payment-card details. See <a href="https://www.revenuecat.com/privacy">RevenueCat’s privacy policy</a> and <a href="https://www.apple.com/legal/privacy/">Apple’s privacy information</a>.</p><p>Railway provides application hosting and database infrastructure. Data is shared with service providers for these functions and may be processed outside your country. We may also disclose information when required by law or necessary to investigate abuse or protect rights.</p>')
    privacy += section('Diagnostics and this website','<p>Operational metrics include request status, latency, usage, and provider cost. Routine application telemetry is designed to exclude raw conversations, source passages, credentials, and full provider-error bodies. Hosting providers may retain their own operational or security logs.</p><p>This static website uses no advertising, tracking scripts, signup forms, or browser storage. GitHub Pages hosts it and logs visitor IP addresses for security. See <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub’s privacy statement</a>. Following an external link opens a service with its own privacy practices.</p>')
    privacy += section('Your choices and requests',f'<p>You can withdraw AI consent, delete local conversations, and clear cached app content in Settings. For access, correction, deletion, or other privacy requests, contact us. We may need proportionate verification to protect records and may retain information required for lawful billing, fraud prevention, or dispute handling. We cannot recover deleted local conversations.</p><p>We will update this page when material processing changes. Provider retention periods and security controls can differ from those of BeliefTrace.</p>{contact()}')
    terms = section('About these terms',f'<p>These terms describe the BeliefTrace iPhone release in preparation, updated {DATE}. Public download and purchases are not yet offered here. Apple’s <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/">Standard Licensed Application End User License Agreement</a> governs the app license; these product and subscription terms supplement it without limiting rights that cannot be waived.</p>{contact()}')
    terms += section('AI interpretation and responsible use','<p>BeliefTrace is for education and intellectual exploration. Responses can be inaccurate, incomplete, offensive, or anachronistic. They are not authentic historical speech or professional medical, mental-health, legal, financial, or emergency advice. A quotation is authentic only when it is explicitly identified and supported by its source; inspect the source before relying on it.</p><p>Do not overload the service, bypass integrity or allowance controls, access private systems, violate another person’s rights, or misrepresent generated text as an authentic quotation. Generation may be temporarily limited or paused to protect users, rights, infrastructure, or provider budgets, including when repeated failed or unusually costly requests consume operational capacity. This can happen while an answer allowance remains; a failed request without a usable answer does not spend that allowance.</p>')
    terms += section('Five successful free answers','<p>The next release includes five successful answers in total per recognized customer identity, shared across thinkers and conversations. This allowance does not reset daily or weekly and is not an Apple subscription introductory offer.</p><p>One answer means one accepted question or follow-up that produces a completed usable response. A legitimate answer explaining that evidence is missing can count. A service failure without a usable answer does not count. Internal model calls are not separate customer messages. Starter questions are editable suggestions and are sent only when you choose.</p><p>The fifth answer remains readable with its evidence. After all five are used, further generation requires an eligible paid allowance. Reading conversations, sources, maps, and saved material remains available without a subscription.</p>')
    terms += section('Weekly subscription',f'<p>{paid}</p><p>Included answers reset at the verified subscription-period boundary shown in the app. Unused answers do not roll over. Restoring, reinstalling, changing the device clock, or refreshing access does not create an additional allowance. Subscription access is verified on the server.</p><p>Apple displays the full localized renewal price and billing period before confirmation. Payment is charged to your Apple Account. A weekly subscription renews automatically unless canceled under Apple’s terms. Cancel at least 24 hours before the current period ends to avoid renewal. Cancellation normally preserves paid access through the verified expiration; expiration, refund, revocation, or an unresolved billing issue can end generation access.</p>')
    terms += section('Manage, restore, and refunds','<p>Use Restore Purchases in Settings or the paywall with the Apple Account that purchased the subscription. Restore recovers eligible purchase access, not local chats. Manage or cancel through <a href="https://apps.apple.com/account/subscriptions">Apple subscription settings</a>. Deleting the app, clearing local data, or withdrawing AI consent does not cancel billing.</p><p>For charges or refund requests, use <a href="https://reportaproblem.apple.com/">Apple’s purchase support</a>. Refund decisions and statutory consumer rights follow Apple’s terms and applicable law.</p>')
    terms += section('Availability and your records','<p>New answers require internet access and working generation and purchase-verification services. Maintenance, outages, exhausted allowances, or security limits can prevent new requests. Previously saved local records and cached material remain accessible in the app where available.</p><p>The mobile app does not offer cloud chat synchronization or a BeliefTrace account. Keep important work separately; deleting local data or losing the device can permanently remove it.</p>')
    support = section('Contact us',contact()+ '<p>We aim to acknowledge ordinary support requests within five business days. Include the app version, iOS version, approximate time of the issue, and the public error code. Please do not include private conversations, receipt contents, account tokens, or credentials in an ordinary support email.</p>')
    support += section('When an answer is unavailable','<ol><li>Check your connection and remaining answer allowance.</li><li>If AI consent was withdrawn, review the disclosure before choosing whether to consent again.</li><li>After a timeout, use the app’s recovery or retry action once. Avoid repeatedly sending the same question.</li><li>During maintenance, you can continue reading local conversations and cached graphs.</li></ol><p>New generation is currently paused while the next release is prepared.</p>')
    support += section('Purchases, restoration, and cancellation','<p>Choose Restore Purchases in Settings or on the paywall using the original Apple Account. Purchase restoration does not restore local chats. Manage or cancel through <a href="https://apps.apple.com/account/subscriptions">Apple subscription settings</a>. Deleting app data does not cancel billing.</p><p>Apple handles payment instruments, billing disputes, and <a href="https://reportaproblem.apple.com/">refund requests</a>. Contact us if Apple shows an active subscription but the app cannot verify it.</p>')
    support += section('Your local work','<p>Delete an individual conversation from the library or history, or use Settings to delete local conversations and clear graph caches. AI-processing consent can be withdrawn while leaving saved chats readable. Important: deleted local chats cannot be recovered by support or Restore Purchases.</p>'+link('/data/','More about your data and deletion'))
    support += section('Accuracy, safety, and rights','<p>For a source error or problematic interpretation, include the thinker, relevant belief or source identifier if available, and a concise description. For copyright or other rights concerns, identify the material and your relationship to the rights holder. The support address also accepts privacy and security reports.</p><p>BeliefTrace is not an emergency service. If you or someone else is in immediate danger, contact local emergency services.</p>')
    safety = section('Think critically','<p>BeliefTrace presents AI interpretations of documented ideas. It is not the historical person, and no historical person or estate endorses the app. Answers can be wrong, biased, incomplete, or offensive. Historical work may contain disturbing or discriminatory views.</p><p>Generated prose is not an authentic quotation. A cited source supports inspection, not a guarantee that every sentence in an answer is correct. Read the original material and compare perspectives when it matters.</p>')
    safety += section('How to read evidence','<p>“Cited” material is identified by the answer contract as supporting the answer. “Related” material was retrieved as context and may not have been cited. Evidence gaps and confidence indicators describe limits in the available support; they are not a measure of philosophical truth.</p><p>Graph edges represent recorded relationships. Visual proximity alone is not evidence of a connection, and a highlighted trace does not reveal the model’s private reasoning.</p>')
    safety += section('When to seek other help','<p>Do not use BeliefTrace for medical, mental-health, legal, financial, emergency, or crisis decisions. Consult an appropriately qualified professional. In immediate danger, contact local emergency services.</p>')
    safety += section('Report a concern',contact())
    data = section('Conversations stay on your iPhone','<p>The mobile app has no BeliefTrace account and does not synchronize your chat library to a cloud account. Conversations, drafts, preferences, and cached graphs are local. Restore Purchases does not restore these records.</p>')
    data += section('Delete or reduce local data','<ol><li>Open the library or history to delete an individual conversation.</li><li>Open Settings to delete local conversations or clear graph caches.</li><li>Withdraw AI-processing consent in Settings to stop new AI requests.</li></ol><p>Confirm the scope before deleting. These actions do not cancel an Apple subscription and do not erase provider records already processed.</p>')
    data += section('Server records and privacy requests','<p>Short-term response-recovery content is retained for up to 48 hours in the next release. You can erase that temporary recovery copy from Settings without a subscription. Content-free request receipts, subscription grants, and spend diagnostics are retained for up to 400 days. Lifetime allowance balances, restore aliases, and hashed transaction mappings are retained while the pseudonymous identity exists. These records are kept separately to honor subscription periods, prevent duplicate work, and enforce the lifetime free allowance.</p><p>For a request concerning server or provider records, contact support. We may ask for an in-app support reference through a suitable channel to verify the request. Do not send credentials or purchase receipts in your first email. Necessary billing, dispute, or anti-abuse records may be retained where appropriate.</p>'+contact())
    records = [('/', 'A good question opens a world', 'Explore philosophical perspectives through conversation, evidence, and connected ideas. BeliefTrace for iPhone is in preparation.', home),('/privacy/','Privacy','How BeliefTrace processes questions, local records, purchases, and diagnostics.',document('Privacy','Your conversations, your choices, and the services involved.',privacy)),('/terms/','Terms & subscriptions','BeliefTrace free answers, weekly subscription information, and Apple license terms.',document('Terms & subscriptions','Clear expectations for curiosity, access, and billing.',terms)),('/support/','Support','Help with BeliefTrace answers, purchases, local history, and content concerns.',document('Support','A useful next step when something gets in the way.',support)),('/safety/','Safety & accuracy','Read BeliefTrace’s AI interpretations and evidence critically.',document('Safety & accuracy','Curiosity works best alongside good judgment.',safety)),('/data/','Your data','Manage local conversations, AI consent, purchase access, and privacy requests.',document('Your data','Keep control of what you save and what you send.',data))]
    for path,title,description,body in records:
        target = OUT / path.strip('/');target.mkdir(exist_ok=True)
        (target/'index.html').write_text(page(path,title,description,body))
    (OUT/'404.html').write_text(page('/404.html','Page not found','Find the information you need about BeliefTrace.',document('A different path.','This page could not be found.',link('/','Return to BeliefTrace','class="button"'))))
    (OUT/'.nojekyll').touch()
    (OUT/'robots.txt').write_text(f'User-agent: *\nAllow: /\nSitemap: {ORIGIN}{BASE}/sitemap.xml\n')
    (OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{ORIGIN}{BASE}{path}</loc><lastmod>2026-09-12</lastmod></url>' for path,*_ in records)+'</urlset>')
    print(f'Built {len(records)} static routes in {OUT}')


if __name__ == '__main__':
    build()
